channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 1cff04e6e86bf372d8ef1751be9415ab7f03c8e6
      hash: sha256-b5lEdu+UeTa/znNR/iHQXu1qrG5gygGscoyXLm22g+4=
      timestamp: '2026-10-03T02:37:56Z'
    packages:
      - name: kernels.haskell
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 19a09b49e746bc4ec4f9a6853a9d6ebdabdbb141
      ref:
        tag: branch
        contents: release-26.05
      hash: sha256-TtrXUvAgpSuI5HMOeZhX+R7ZmUvt1zcSRA7wYPEQS4A=
      timestamp: '2026-10-03T07:32:56Z'
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
