channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: f49e186b2ef316f741aba9c5414901a8b8918aaa
      hash: sha256-AW8EhYyowL0c56cv6ynBu40mTsQnlznmDs11wKZZZYM=
      timestamp: '2026-06-26T05:46:34Z'
    packages:
      - name: kernels.rust
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 1d4e0f865d68258aada31e68e6d79c8c463f3b34
      hash: sha256-db/8NgfehQlPNt8rMY0J1gvwzTaURU/foM7y/AQimIM=
      timestamp: '2026-06-29T21:05:57Z'
      ref:
        tag: branch
        contents: release-25.11
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
