channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 841eecc5756cc109d73649d70aaf4cad67c8335d
      hash: sha256-ya7tUEfash5CJXgT64/sjx70bfUE3QIYhxsa2SXPAdU=
      timestamp: '2026-06-09T21:29:35Z'
    packages:
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: d776225b15cd4ef06f9ee232975955a0c5105658
      ref:
        tag: branch
        contents: release-25.11
      hash: sha256-AAxYt25ftx04wBOiiBIovSqNhrv9GfeubXwvz0AVYYA=
      timestamp: '2026-06-09T21:09:33Z'
    packages: []
