channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 19a5589fa5c347771a46b0eb25174a28b28f30f2
      hash: sha256-eHO4jbJ7+W760DL+yRwm0mT8kvIEoVugnEzq7i4ixIw=
      timestamp: '2026-08-07T02:27:54Z'
    packages:
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: cd648d6ea62bc0ffba91e61fcfe5e33c1e2004b1
      ref:
        tag: branch
        contents: release-25.11
      hash: sha256-pg6hLjDeAWaUOzh2JM2Cw0BwYpGtOyNr6A4FBwP9Ymo=
      timestamp: '2026-07-06T22:09:36Z'
    packages: []
