channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 5936a3f045277d2478750e92395d82644f90be5d
      hash: sha256-Q5oJ4DyM2DWq2FZ9JE6+yhwb683EIF2DjBjhv/BE4cs=
      timestamp: '2026-07-03T01:20:04Z'
    packages:
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 0921fdb3e13e40fe25fbc52b89661a9d6d32ac68
      ref:
        tag: branch
        contents: release-25.11
      hash: sha256-ESJ4VgytmAt+98YLM8466luln4HyEZ9Q36b9+Bb4P5w=
      timestamp: '2026-07-01T11:22:33Z'
    packages: []
