channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 891ca9f7f7dbccdaddf871110273f3b850407180
      hash: sha256-/J9PsK34ndejR4yWERwaYNXGWItF7zpW7dP9KOgkh8w=
      timestamp: '2026-06-09T07:49:33Z'
    packages:
      - name: kernels.go
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: fb4eb89fa6a4cb5c7bf9c47fb54b77a3c44efd88
      hash: sha256-klzn9mBbtQvbTq++0B5KKNWT4pzTF+0SGo7Q2ylJsdg=
      timestamp: '2026-06-09T18:12:23Z'
      ref:
        tag: branch
        contents: release-25.11
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
