channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 5c7b0da26d06a77d87a8caf78ec41cac392cbc8c
      hash: sha256-4ddFMKmUQPY/AOEFquYaFahYGtUF1j7frEw9jb+NfQs=
      timestamp: '2026-07-10T11:49:54Z'
    packages:
      - name: kernels.cpp
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 0cf1b4f2c3ebd28764715903b078119e2ab4bc1c
      hash: sha256-D6gdamo1g6ptvXtFPNS19C7yEtKPvputhkpEL7NCt/o=
      timestamp: '2026-07-30T23:49:33Z'
      ref:
        tag: branch
        contents: release-26.05
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
