channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 1cff04e6e86bf372d8ef1751be9415ab7f03c8e6
      hash: sha256-b5lEdu+UeTa/znNR/iHQXu1qrG5gygGscoyXLm22g+4=
      timestamp: '2026-10-03T02:37:56Z'
    packages:
      - name: kernels.cpp
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 59b350fb085161834e5ab9b15d26800b64299345
      hash: sha256-rUA/xXBozfq4z/xXTR5Vv19UOAMYxogdoM3UfqKPa/w=
      timestamp: '2026-10-03T23:49:23Z'
      ref:
        tag: branch
        contents: release-26.05
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
