channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 7aeae06a979b4cf9fcefcae4c1c12ae93b0c6c73
      hash: sha256-BOQ1DNP6iIk9zA6H8zPHTmBS9bdqOr8MEpxS53TIvhU=
      timestamp: '2026-03-03T10:11:25Z'
    packages:
      - name: kernels.coq
        settings:
          enable: true
        packages:
          - name: bignums
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 47aea2b40a6de16dcbc4b4cf6bab3fd779b8678c
      hash: sha256-Tk/Y60I6ldjeFbM7ZTzNbXcZUPMOtGrR37fh3AY5qow=
      timestamp: '2026-03-03T08:27:17Z'
      ref:
        tag: branch
        contents: release-25.11
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
