channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 1cff04e6e86bf372d8ef1751be9415ab7f03c8e6
      hash: sha256-b5lEdu+UeTa/znNR/iHQXu1qrG5gygGscoyXLm22g+4=
      timestamp: '2026-10-03T02:37:56Z'
    packages:
      - name: kernels.coq
        settings:
          enable: true
        packages:
          - name: bignums
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 9d792c97015f02bccf43cdb3fb126380a1dacbb1
      hash: sha256-RpIami/C213gSBQDhbRt7wXLwRkmjXNgywbnKNt/VLk=
      timestamp: '2026-10-04T02:44:33Z'
      ref:
        tag: branch
        contents: release-26.05
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
