channels:
- name: codedown
  special: true
  src:
    owner: codedownio
    repo: codedown-languages
    rev: ae6044046a74b85966a8b35c1024b1571db5832d
    sha256: 1hdjz8bk4mpd14qn8wybmjnvp8fg2v9raravi14va9svk2xwh6m2
    tag: fetch_from_github
- name: nixpkgs
  src:
    owner: NixOS
    ref:
      contents: release-23.11
      tag: branch
    repo: nixpkgs
    rev: 1bf7d3e7d2aaa667365fb3bc8673760ffbaca7bb
    sha256: 2xE31a0G1jGbK5u4CKK8AkyJtB37XQkh6lEW0J518YQ=
    tag: fetch_from_github
kernels:
- name: python3
  packages:
  - name: matplotlib
    meta:
      changelog: https://github.com/matplotlib/matplotlib/releases/tag/v3.7.0
      description: Python plotting library, making publication quality plots
      homepage: https://matplotlib.org/
      maintainers:
      - name: Jason O'Conal
        email: jason@oconal.id.au
        github: lovek323
        githubId: 265084
      - name: Dmitry Kalinkin
        email: veprbl@gmail.com
        github: veprbl
        githubId: 245573
      version: 3.7.0
  channel: codedown
  meta:
    display_name: Python 3.10.11
    changelog: https://docs.python.org/release/3.10.11/whatsnew/changelog.html
    description: A high-level dynamically-typed programming language
    homepage: https://www.python.org
    icon: /nix/store/1ffcsg6qq21d4m2mfz9yqz0ypi93m0hq-python-logo-64x64.png
    maintainers:
    - name: Frederik Rietdijk
      email: fridh@fridh.nl
      github: FRidh
      githubId: 2129135
    modes:
      attrs:
      - python3
      - python
      code_mirror_mode: python
      extensions:
      - py
    settings_schema:
    - level: 1
      title: Language servers
      type: heading
    - defaultValue: true
      target: lsp.jedi.enable
      title: Enable Jedi language server
      type: boolean
    - defaultValue: false
      target: lsp.pyright.enable
      title: Enable Pyright language server
      type: boolean
    - defaultValue: false
      target: lsp.pylint.enable
      title: Enable Pylint language server
      type: boolean
    - defaultValue: false
      target: lsp.flake8.enable
      title: Enable Flake8 language server
      type: boolean
    - defaultValue: false
      target: lsp.pycodestyle.enable
      title: Enable pycodestyle language server
      type: boolean
    - defaultValue: false
      target: lsp.microsoft.enable
      title: Enable Microsoft Python language server
      type: boolean
    - defaultValue: false
      target: lsp.python-lsp-server.enable
      title: Enable python-lsp-server language server
      type: boolean
    - defaultValue: false
      target: lsp.python-language-server.enable
      title: Enable python-language-server language server
      type: boolean
    - level: 1
      title: Miscellaneous
      type: heading
    - defaultValue: false
      description: Skip setting the PYTHONNOUSERSITE variable. This will allow your
        Python code to import local packages (e.g. from ~/.local/lib). This is useful
        if you want to use pip to install Python packages independently of Nix.
      target: permitUserSite
      title: Permit user site-packages
      type: boolean
    - defaultValue: true
      description: Enable the variable inspector, which will fetch runtime values
        of variables to show in the variables list.
      target: enableVariableInspector
      title: Enable variable inspector
      type: boolean
    spdx_id: Python-2.0
  modes:
    attrs:
    - python3
    - python
    code_mirror_mode: python
    extensions:
    - py
  settings:
    enableVariableInspector: true
    lsp.flake8.enable: false
    lsp.jedi.enable: true
    lsp.microsoft.enable: false
    lsp.pycodestyle.enable: false
    lsp.pylint.enable: false
    lsp.pyright.enable: false
    lsp.python-language-server.enable: false
    lsp.python-lsp-server.enable: false
    permitUserSite: false
- name: bash
  packages: []
  channel: codedown
  meta:
    display_name: Bash 5.2
    description: GNU Bourne-Again Shell, the de facto standard shell on Linux
    homepage: https://www.gnu.org/software/bash/
    icon: /nix/store/rq7n1n9chh3kw9gjj4mfawq8jq2ixbi1-bash-logo-128x128.png
    maintainers:
    - name: Will Dietz
      email: w@wdtz.org
      github: dtzWill
      githubId: 817330
      keys:
      - fingerprint: 389A 78CB CD88 5E0C 4701  DEB9 FD42 C7D0 D414 94C8
    modes:
      attrs:
      - bash
      code_mirror_mode: shell
      extensions:
      - sh
      - bash
    settings_schema:
    - defaultValue: true
      target: lsp.bash-language-server.enable
      title: Enable Bash language server
      type: boolean
    spdx_id: GPL-3.0-or-later
  modes:
    attrs:
    - bash
    code_mirror_mode: shell
    extensions:
    - sh
    - bash
  settings: {}
other_packages:
- attr: shells.zsh
  channel: codedown
  meta:
    description: The Z shell
    homepage: https://www.zsh.org/
    maintainers:
    - name: Pascal Wittmann
      email: mail@pascal-wittmann.de
      github: pSub
      githubId: 83842
    - name: Artturi N
      email: artturin@artturin.com
      github: Artturin
      githubId: 56650223
      matrix: '@artturin:matrix.org'
    version: '5.9'
- attr: spellchecker
  channel: codedown
  meta:
    description: Spell checker
    homepage: https://hunspell.sourceforge.net
    maintainers: []
