channels:
- name: codedown
  packages:
  - name: kernels.python3
    packages:
    - name: matplotlib
      packages: []
      meta:
        name: python3.11-matplotlib-3.8.4
        changelog: https://github.com/matplotlib/matplotlib/releases/tag/v3.8.4
        description: Python plotting library, making publication quality plots
        homepage: https://matplotlib.org/
        maintainers:
        - name: Jason O'Conal
          email: jason@oconal.id.au
          github: lovek323
          githubId: 265084
        - name: Dmitry Kalinkin
          email: veprbl@gmail.com
          github: veprbl
          githubId: 245573
        version: 3.8.4
      settings: null
    meta:
      name: python3-3.11.9
      display_name: Python 3.11.9
      changelog: https://docs.python.org/release/3.11.9/whatsnew/changelog.html
      description: A high-level dynamically-typed programming language
      has_packages: true
      homepage: https://www.python.org
      icon: /nix/store/1ffcsg6qq21d4m2mfz9yqz0ypi93m0hq-python-logo-64x64.png
      language_server_names:
      - jedi
      modes:
        attrs:
        - python
        code_mirror_mode: python
        extensions:
        - py
      settings_schema:
        packages:
          defaultValue: []
          listType:
            left:
              type: string
            right:
              type: attrs
            type: either
          type: list
        enable:
          defaultValue: false
          description: Enable Python 3 kernel
          hidden: true
          title: Enable Python 3 kernel
          type: boolean
        interface.attrs:
          defaultValue:
          - python
          description: Notebook cells that have these attributes will match this kernel,
            allowing it to run the code.
          listType:
            type: string
          title: Notebook attributes
          type: list
        interface.extensions:
          defaultValue:
          - py
          description: Files with these extensions will match against this kernel,
            allowing you to run the code as if it were a Jupyter cell.
          listType:
            type: string
          title: File extensions
          type: list
        lsp.flake8.enable:
          defaultValue: false
          description: Enable Flake8 language server
          type: boolean
        lsp.jedi.enable:
          defaultValue: true
          title: Enable Jedi language server
          type: boolean
        lsp.microsoft.enable:
          defaultValue: false
          description: Enable Microsoft Python language server
          type: boolean
        lsp.pycodestyle.enable:
          defaultValue: false
          description: Enable pycodestyle language server
          type: boolean
        lsp.pylint.enable:
          defaultValue: false
          description: Enable Pylint language server
          type: boolean
        lsp.pyright.enable:
          defaultValue: false
          description: Enable Pyright language server
          type: boolean
        lsp.python-language-server.enable:
          defaultValue: false
          description: Enable python-language-server language server
          type: boolean
        lsp.python-lsp-server.enable:
          defaultValue: false
          description: Enable python-lsp-server language server
          type: boolean
        misc.enableVariableInspector:
          defaultValue: true
          description: This will show a summary of the currently defined variables
            in the UI.
          title: Enable the variable inspector
          type: boolean
        misc.permitUserSite:
          defaultValue: false
          description: Skip setting the PYTHONNOUSERSITE variable. This will allow
            your Python code to import local packages (e.g. from ~/.local/lib). This
            is useful if you want to use pip to install Python packages independently
            of Nix.
          title: Permit user site-packages
          type: boolean
        python3Package:
          defaultValue: python3
          title: Python 3 version
          type: enum
          values:
          - python3
          - python310
          - python311
          - python312
          - python313
          - python39
      spdx_id: Python-2.0
    settings:
      packages:
      - matplotlib
      enable: true
  - name: kernels.bash
    packages: []
    meta:
      name: bash-5.2p26
      display_name: Bash 5.2p26
      description: GNU Bourne-Again Shell, the de facto standard shell on Linux
      has_packages: false
      homepage: https://www.gnu.org/software/bash/
      icon: /nix/store/rq7n1n9chh3kw9gjj4mfawq8jq2ixbi1-bash-logo-128x128.png
      language_server_names:
      - bash-language-server
      maintainers:
      - name: Will Dietz
        email: w@wdtz.org
        github: dtzWill
        githubId: 817330
        keys:
        - fingerprint: 389A 78CB CD88 5E0C 4701  DEB9 FD42 C7D0 D414 94C8
      modes:
        attrs:
        - bash
        code_mirror_mode: shell
        extensions:
        - sh
        - bash
      settings_schema:
        attrs:
          defaultValue:
          - bash
          listType:
            type: string
          type: list
        enable:
          defaultValue: false
          description: Enable Bash kernel
          hidden: true
          type: boolean
        extensions:
          defaultValue:
          - sh
          - bash
          listType:
            type: string
          type: list
        lsp.bash-language-server.enable:
          defaultValue: true
          description: Enable Bash language server
          type: boolean
      spdx_id: GPL-3.0-or-later
    settings:
      enable: true
  - name: shells.zsh
    packages: []
    meta:
      name: zsh-5.9
      display_name: ZSH 5.9
      description: The Z shell
      homepage: https://www.zsh.org/
      icon: /nix/store/7j21ks0fgsx1vbpigkc044i4ahbr7s9p-default_icon_64x64.png
      maintainers:
      - name: Pascal Wittmann
        email: mail@pascal-wittmann.de
        github: pSub
        githubId: 83842
      - name: Artturi N
        email: artturin@artturin.com
        github: Artturin
        githubId: 56650223
        matrix: '@artturin:matrix.org'
      version: '5.9'
    settings: {}
  - name: language-servers.spellchecker
    packages: []
    meta:
      name: hunspell-1.7.2
      display_name: Spellchecker 1.1.0
      category: Language servers
      description: Spell checker
      homepage: https://hunspell.sourceforge.net
      icon: /nix/store/iv0l66606331c2463l17avxrk4j2wjai-pen-alt.png
      language_server_names:
      - spellchecker
      maintainers: []
    settings: {}
  src:
    tag: fetch_from_github
    owner: codedownio
    repo: codedown-languages
    rev: 1f1b5741a2a143f3c77260f31fe8b0b6ea8d1dc2
    hash: sha256-qolQvvvdENLWRpC7Gt++KmqCXzJr3tuJWf2qe8PvzVI=
    timestamp: 2024-09-25T10:20:03Z
  special: true
- name: nixpkgs
  packages: []
  src:
    tag: fetch_from_github
    owner: NixOS
    repo: nixpkgs
    rev: 205fd4226592cc83fd4c0885a3e4c9c400efabb5
    hash: sha256-zwVvxrdIzralnSbcpghA92tWu2DV2lwv89xZc8MTrbg=
    timestamp: 2024-07-09T14:26:38Z
    ref:
      tag: branch
      contents: release-23.11
