channels:
  - name: codedown
    src:
      sha256: 1wgm3yx8ziybn4ykv6xazd74dw5wdzmshb3q07vfy2zi314bfvaq
      repo: codedown-languages
      rev: 442642ed5dec4f2c9d96b057547fec50c7caa784
      tag: fetch_from_github
      owner: codedownio
    special: true
    overlays: []
  - name: nixpkgs
    src:
      repo: nixpkgs
      ref:
        tag: branch
        contents: release-22.11
      rev: 523b39618444fa921d3230c8f10f1563612d785d
      sha256: DVKPeIZqzkNOOsxxx6iHTg2J+R/8hLWZLppK25ixD00=
      tag: fetch_from_github
      owner: NixOS
    overlays: []
kernels:
  - name: python311
    display_name: Python 3.11
    packages:
      - name: matplotlib
    icon: /nix/store/kjbx4pcf72bhhrl264z646i3pwy61cgx-logo-64x64.png
    channel: codedown
    settings:
      permitUserSite: false
      enableVariableInspector: true
  - name: bashInteractive
    display_name: Bash 5.1
    packages: []
    icon: /nix/store/ms4228wqkviv0c3qn6m1crkgzfkd07l1-bash.png
    channel: codedown
other_packages:
  - name: zsh-5.8.1
    channel: codedown
    attr: shells.zsh
  - name: codedown-spellchecker
    channel: codedown
    attr: spellchecker
