channels:
- name: codedown
  special: true
  src:
    owner: codedownio
    repo: codedown-languages
    rev: b1c4a43b1778c8c74ad5198b3ff3daa52d0ba1e9
    sha256: 1v08q4ll7nh071iahlf3slq7vzf740312fqf3pchz7y08rfis1jg
    tag: fetch_from_github
- name: nixpkgs
  src:
    owner: NixOS
    ref:
      contents: release-23.11
      tag: branch
    repo: nixpkgs
    rev: 3bc91a8eac7e96d263d7a4d96510f0ab3e09e2f9
    sha256: 1hHb9dCsEaUordnd3n5mHKWn0amGICALpxllrKwE6ZQ=
    tag: fetch_from_github
kernels:
- name: python3
  display_name: Python 3.10.11
  packages:
  - matplotlib
  channel: codedown
  icon: /nix/store/1ffcsg6qq21d4m2mfz9yqz0ypi93m0hq-python-logo-64x64.png
  modes:
    attrs:
    - python3
    - python
    code_mirror_mode: python
    extensions:
    - py
  settings:
    enableVariableInspector: true
    lsp.flake8.enable: false
    lsp.jedi.enable: true
    lsp.microsoft.enable: false
    lsp.pycodestyle.enable: false
    lsp.pylint.enable: false
    lsp.pyright.enable: false
    lsp.python-language-server.enable: false
    lsp.python-lsp-server.enable: false
    permitUserSite: false
  settings_schema:
  - level: 1
    title: Language servers
    type: heading
  - defaultValue: true
    target: lsp.jedi.enable
    title: Enable Jedi language server
    type: boolean
  - defaultValue: false
    target: lsp.pyright.enable
    title: Enable Pyright language server
    type: boolean
  - defaultValue: false
    target: lsp.pylint.enable
    title: Enable Pylint language server
    type: boolean
  - defaultValue: false
    target: lsp.flake8.enable
    title: Enable Flake8 language server
    type: boolean
  - defaultValue: false
    target: lsp.pycodestyle.enable
    title: Enable pycodestyle language server
    type: boolean
  - defaultValue: false
    target: lsp.microsoft.enable
    title: Enable Microsoft Python language server
    type: boolean
  - defaultValue: false
    target: lsp.python-lsp-server.enable
    title: Enable python-lsp-server language server
    type: boolean
  - defaultValue: false
    target: lsp.python-language-server.enable
    title: Enable python-language-server language server
    type: boolean
  - level: 1
    title: Miscellaneous
    type: heading
  - defaultValue: false
    description: Skip setting the PYTHONNOUSERSITE variable. This will allow your
      Python code to import local packages (e.g. from ~/.local/lib). This is useful
      if you want to use pip to install Python packages independently of Nix.
    target: permitUserSite
    title: Permit user site-packages
    type: boolean
  - defaultValue: true
    description: Enable the variable inspector, which will fetch runtime values of
      variables to show in the variables list.
    target: enableVariableInspector
    title: Enable variable inspector
    type: boolean
- name: bash
  display_name: Bash 5.2
  packages: []
  channel: codedown
  icon: /nix/store/rq7n1n9chh3kw9gjj4mfawq8jq2ixbi1-bash-logo-128x128.png
  modes:
    attrs:
    - bash
    code_mirror_mode: shell
    extensions:
    - sh
    - bash
  settings: {}
  settings_schema:
  - defaultValue: true
    target: lsp.bash-language-server.enable
    title: Enable Bash language server
    type: boolean
other_packages:
- attr: shells.zsh
  channel: codedown
  meta:
    description: The Z shell
    homepage: https://www.zsh.org/
    maintainers:
    - name: Pascal Wittmann
      email: mail@pascal-wittmann.de
      github: pSub
      githubId: 83842
    - name: Artturi N
      email: artturin@artturin.com
      github: Artturin
      githubId: 56650223
      matrix: '@artturin:matrix.org'
    version: '5.9'
- attr: spellchecker
  channel: codedown
  meta:
    description: Spell checker
    homepage: https://hunspell.sourceforge.net
    maintainers: []
