channels:
- name: codedown
  packages:
  - name: kernels.python3
    packages:
    - name: matplotlib
      packages: []
      meta:
        name: python3.11-matplotlib-3.8.4
        changelog: https://github.com/matplotlib/matplotlib/releases/tag/v3.8.4
        description: Python plotting library, making publication quality plots
        homepage: https://matplotlib.org/
        maintainers:
        - name: Jason O'Conal
          email: jason@oconal.id.au
          github: lovek323
          githubId: 265084
        - name: Dmitry Kalinkin
          email: veprbl@gmail.com
          github: veprbl
          githubId: 245573
        version: 3.8.4
      settings: null
    meta:
      name: python3-3.11.9
      display_name: Python 3.11.9
      changelog: https://docs.python.org/release/3.11.9/whatsnew/changelog.html
      description: A high-level dynamically-typed programming language
      has_packages: true
      homepage: https://www.python.org
      icon: /nix/store/1ffcsg6qq21d4m2mfz9yqz0ypi93m0hq-python-logo-64x64.png
      language_server_names:
      - jedi
      modes:
        attrs:
        - python
        code_mirror_mode: python
        extensions:
        - py
      settings_schema:
      - defaultValue: 'false'
        description: Enable Python 3 kernel
        hidden: true
        loc:
        - enable
        target: kernels.python3.enable
        title: Enable Python 3 kernel
        type: boolean
      - defaultValue: '["python"]'
        description: Notebook cells that have these attributes will match this kernel,
          allowing it to run the code.
        listType:
          type: string
        loc:
        - interface
        - attrs
        target: kernels.python3.interface.attrs
        title: Notebook attributes
        type: list
      - defaultValue: '["py"]'
        description: Files with these extensions will match against this kernel, allowing
          you to run the code as if it were a Jupyter cell.
        listType:
          type: string
        loc:
        - interface
        - extensions
        target: kernels.python3.interface.extensions
        title: File extensions
        type: list
      - defaultValue: 'false'
        description: Enable Flake8 language server
        loc:
        - lsp
        - flake8
        - enable
        target: kernels.python3.lsp.flake8.enable
        type: boolean
      - defaultValue: 'true'
        loc:
        - lsp
        - jedi
        - enable
        target: kernels.python3.lsp.jedi.enable
        title: Enable Jedi language server
        type: boolean
      - defaultValue: 'false'
        description: Enable Microsoft Python language server
        loc:
        - lsp
        - microsoft
        - enable
        target: kernels.python3.lsp.microsoft.enable
        type: boolean
      - defaultValue: 'false'
        description: Enable pycodestyle language server
        loc:
        - lsp
        - pycodestyle
        - enable
        target: kernels.python3.lsp.pycodestyle.enable
        type: boolean
      - defaultValue: 'false'
        description: Enable Pylint language server
        loc:
        - lsp
        - pylint
        - enable
        target: kernels.python3.lsp.pylint.enable
        type: boolean
      - defaultValue: 'false'
        description: Enable Pyright language server
        loc:
        - lsp
        - pyright
        - enable
        target: kernels.python3.lsp.pyright.enable
        type: boolean
      - defaultValue: 'false'
        description: Enable python-language-server language server
        loc:
        - lsp
        - python-language-server
        - enable
        target: kernels.python3.lsp.python-language-server.enable
        type: boolean
      - defaultValue: 'false'
        description: Enable python-lsp-server language server
        loc:
        - lsp
        - python-lsp-server
        - enable
        target: kernels.python3.lsp.python-lsp-server.enable
        type: boolean
      - defaultValue: 'true'
        description: This will show a summary of the currently defined variables in
          the UI.
        loc:
        - misc
        - enableVariableInspector
        target: kernels.python3.misc.enableVariableInspector
        title: Enable the variable inspector
        type: boolean
      - defaultValue: 'false'
        description: Skip setting the PYTHONNOUSERSITE variable. This will allow your
          Python code to import local packages (e.g. from ~/.local/lib). This is useful
          if you want to use pip to install Python packages independently of Nix.
        loc:
        - misc
        - permitUserSite
        target: kernels.python3.misc.permitUserSite
        title: Permit user site-packages
        type: boolean
      - defaultValue: '[]'
        listType:
          left:
            type: string
          right:
            type: attrs
          type: either
        loc:
        - packages
        target: kernels.python3.packages
        type: list
      - defaultValue: '"python3"'
        description: Python 3 version
        loc:
        - python3Package
        target: kernels.python3.python3Package
        type: enum
        values:
        - python3
        - python3
        - python310
        - python311
        - python312
        - python313
        - python39
      spdx_id: Python-2.0
    settings:
      packages:
      - matplotlib
      enable: true
      interface:
        attrs:
        - python
        extensions:
        - py
      lsp:
        flake8:
          enable: false
        jedi:
          enable: true
        microsoft:
          enable: false
        pycodestyle:
          enable: false
        pylint:
          enable: false
        pyright:
          enable: false
        python-language-server:
          enable: false
        python-lsp-server:
          enable: false
      misc:
        enableVariableInspector: true
        permitUserSite: false
      python3Package: python3
  - name: kernels.bash
    packages: []
    meta:
      name: bash-5.2p26
      display_name: Bash 5.2p26
      description: GNU Bourne-Again Shell, the de facto standard shell on Linux
      has_packages: false
      homepage: https://www.gnu.org/software/bash/
      icon: /nix/store/rq7n1n9chh3kw9gjj4mfawq8jq2ixbi1-bash-logo-128x128.png
      language_server_names:
      - bash-language-server
      maintainers:
      - name: Will Dietz
        email: w@wdtz.org
        github: dtzWill
        githubId: 817330
        keys:
        - fingerprint: 389A 78CB CD88 5E0C 4701  DEB9 FD42 C7D0 D414 94C8
      modes:
        attrs:
        - bash
        code_mirror_mode: shell
        extensions:
        - sh
        - bash
      settings_schema:
      - defaultValue: '["bash"]'
        listType:
          type: string
        loc:
        - attrs
        target: kernels.bash.attrs
        type: list
      - defaultValue: 'false'
        description: Enable Bash kernel
        hidden: true
        loc:
        - enable
        target: kernels.bash.enable
        type: boolean
      - defaultValue: '["sh","bash"]'
        listType:
          type: string
        loc:
        - extensions
        target: kernels.bash.extensions
        type: list
      - defaultValue: 'true'
        description: Enable Bash language server
        loc:
        - lsp
        - bash-language-server
        - enable
        target: kernels.bash.lsp.bash-language-server.enable
        type: boolean
      spdx_id: GPL-3.0-or-later
    settings:
      attrs:
      - bash
      enable: true
      extensions:
      - sh
      - bash
      lsp:
        bash-language-server:
          enable: true
  - name: shells.zsh
    packages: []
    meta:
      name: zsh-5.9
      display_name: ZSH 5.9
      description: The Z shell
      homepage: https://www.zsh.org/
      icon: /nix/store/7j21ks0fgsx1vbpigkc044i4ahbr7s9p-default_icon_64x64.png
      maintainers:
      - name: Pascal Wittmann
        email: mail@pascal-wittmann.de
        github: pSub
        githubId: 83842
      - name: Artturi N
        email: artturin@artturin.com
        github: Artturin
        githubId: 56650223
        matrix: '@artturin:matrix.org'
      version: '5.9'
    settings: {}
  - name: language-servers.spellchecker
    packages: []
    meta:
      name: hunspell-1.7.2
      display_name: Spellchecker 1.1.0
      category: Language servers
      description: Spell checker
      homepage: https://hunspell.sourceforge.net
      icon: /nix/store/iv0l66606331c2463l17avxrk4j2wjai-pen-alt.png
      language_server_names:
      - spellchecker
      maintainers: []
    settings: {}
  src:
    tag: fetch_from_github
    owner: codedownio
    repo: codedown-languages
    rev: f30464dc0aadfd264b06a6f624db30611a4cb254
    hash: sha256-ZpJPH9VN8nNBUGioYwLBMrK9q97CtKukie1+AdJFk1Q=
    timestamp: 2024-09-25T01:01:11Z
  special: true
- name: nixpkgs
  packages: []
  src:
    tag: fetch_from_github
    owner: NixOS
    repo: nixpkgs
    rev: 205fd4226592cc83fd4c0885a3e4c9c400efabb5
    hash: sha256-zwVvxrdIzralnSbcpghA92tWu2DV2lwv89xZc8MTrbg=
    timestamp: 2024-07-09T14:26:38Z
    ref:
      tag: branch
      contents: release-23.11
