channels:
- name: codedown
  src:
    tag: fetch_from_github
    owner: codedownio
    repo: codedown-languages
    rev: aa0c7e9df2e78173e41c9ade31aa1f8298594f97
    hash: sha256-HwSBWzS3mvVAzpOfKaiMY7Rh3Mk75LKcn8Ay8mVbN9Y=
    timestamp: 2024-08-07T10:26:45Z
  special: true
- name: nixpkgs
  src:
    tag: fetch_from_github
    owner: NixOS
    repo: nixpkgs
    rev: 205fd4226592cc83fd4c0885a3e4c9c400efabb5
    hash: sha256-zwVvxrdIzralnSbcpghA92tWu2DV2lwv89xZc8MTrbg=
    timestamp: 2024-07-09T14:26:38Z
    ref:
      tag: branch
      contents: release-23.11
kernels:
- name: python3
  packages:
  - name: matplotlib
    meta:
      name: python3.11-matplotlib-3.8.4
      changelog: https://github.com/matplotlib/matplotlib/releases/tag/v3.8.4
      description: Python plotting library, making publication quality plots
      homepage: https://matplotlib.org/
      maintainers:
      - name: Jason O'Conal
        email: jason@oconal.id.au
        github: lovek323
        githubId: 265084
      - name: Dmitry Kalinkin
        email: veprbl@gmail.com
        github: veprbl
        githubId: 245573
      version: 3.8.4
  channel: codedown
  meta:
    name: python3-3.11.9
    display_name: Python 3.11.9
    changelog: https://docs.python.org/release/3.11.9/whatsnew/changelog.html
    description: A high-level dynamically-typed programming language
    homepage: https://www.python.org
    icon: /nix/store/1ffcsg6qq21d4m2mfz9yqz0ypi93m0hq-python-logo-64x64.png
    language_server_names:
    - jedi
    modes:
      attrs:
      - python3
      - python
      code_mirror_mode: python
      extensions:
      - py
    settings_schema:
    - level: 1
      title: Language servers
      type: heading
    - defaultValue: true
      target: lsp.jedi.enable
      title: Enable Jedi language server
      type: boolean
    - defaultValue: false
      target: lsp.pyright.enable
      title: Enable Pyright language server
      type: boolean
    - defaultValue: false
      target: lsp.pylint.enable
      title: Enable Pylint language server
      type: boolean
    - defaultValue: false
      target: lsp.flake8.enable
      title: Enable Flake8 language server
      type: boolean
    - defaultValue: false
      target: lsp.pycodestyle.enable
      title: Enable pycodestyle language server
      type: boolean
    - defaultValue: false
      target: lsp.microsoft.enable
      title: Enable Microsoft Python language server
      type: boolean
    - defaultValue: false
      target: lsp.python-lsp-server.enable
      title: Enable python-lsp-server language server
      type: boolean
    - defaultValue: false
      target: lsp.python-language-server.enable
      title: Enable python-language-server language server
      type: boolean
    - level: 1
      title: Miscellaneous
      type: heading
    - defaultValue: false
      description: Skip setting the PYTHONNOUSERSITE variable. This will allow your
        Python code to import local packages (e.g. from ~/.local/lib). This is useful
        if you want to use pip to install Python packages independently of Nix.
      target: permitUserSite
      title: Permit user site-packages
      type: boolean
    - defaultValue: true
      description: Enable the variable inspector, which will fetch runtime values
        of variables to show in the variables list.
      target: enableVariableInspector
      title: Enable variable inspector
      type: boolean
    spdx_id: Python-2.0
  settings:
    enableVariableInspector: true
    lsp.flake8.enable: false
    lsp.jedi.enable: true
    lsp.microsoft.enable: false
    lsp.pycodestyle.enable: false
    lsp.pylint.enable: false
    lsp.pyright.enable: false
    lsp.python-language-server.enable: false
    lsp.python-lsp-server.enable: false
    permitUserSite: false
- name: bash
  packages: []
  channel: codedown
  meta:
    name: bash-5.2p26
    display_name: Bash 5.2p26
    description: GNU Bourne-Again Shell, the de facto standard shell on Linux
    homepage: https://www.gnu.org/software/bash/
    icon: /nix/store/rq7n1n9chh3kw9gjj4mfawq8jq2ixbi1-bash-logo-128x128.png
    language_server_names:
    - bash-language-server
    maintainers:
    - name: Will Dietz
      email: w@wdtz.org
      github: dtzWill
      githubId: 817330
      keys:
      - fingerprint: 389A 78CB CD88 5E0C 4701  DEB9 FD42 C7D0 D414 94C8
    modes:
      attrs:
      - bash
      code_mirror_mode: shell
      extensions:
      - sh
      - bash
    settings_schema:
    - defaultValue: true
      target: lsp.bash-language-server.enable
      title: Enable Bash language server
      type: boolean
    spdx_id: GPL-3.0-or-later
  settings: {}
other_packages:
- attr: shells.zsh
  channel: codedown
  meta:
    name: zsh-5.9
    display_name: ZSH 5.9
    category: Shells
    description: The Z shell
    homepage: https://www.zsh.org/
    icon: /nix/store/7j21ks0fgsx1vbpigkc044i4ahbr7s9p-default_icon_64x64.png
    maintainers:
    - name: Pascal Wittmann
      email: mail@pascal-wittmann.de
      github: pSub
      githubId: 83842
    - name: Artturi N
      email: artturin@artturin.com
      github: Artturin
      githubId: 56650223
      matrix: '@artturin:matrix.org'
    version: '5.9'
- attr: spellchecker
  channel: codedown
  meta:
    name: hunspell-1.7.2
    category: Language servers
    description: Spell checker
    homepage: https://hunspell.sourceforge.net
    icon: /nix/store/iv0l66606331c2463l17avxrk4j2wjai-pen-alt.png
    language_server_names:
    - spellchecker
    maintainers: []
