channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 8f33eb70fe1d9171b54162b34b13f286ed624141
      hash: sha256-RXnHyFhdzr5+Wq9dNh/87eYSTj3/JfmjkvWy2N/MQPE=
      timestamp: '2026-08-07T09:24:26Z'
    packages:
      - name: kernels.julia
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: cd648d6ea62bc0ffba91e61fcfe5e33c1e2004b1
      hash: sha256-pg6hLjDeAWaUOzh2JM2Cw0BwYpGtOyNr6A4FBwP9Ymo=
      timestamp: '2026-07-06T22:09:36Z'
      ref:
        tag: branch
        contents: release-25.11
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
