channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 337090657d6ab73b8edcd6b8309fedee5e7a54e3
      hash: sha256-KSKIODWdrBn6CQmq32NfJJErKzlPSAxhmmsD9Oe6lnE=
      timestamp: '2026-03-05T07:26:30Z'
    packages:
      - name: kernels.julia
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 20f276a6030e95682d3693780ae6c2f40113931e
      hash: sha256-QvhXjtLuHlvRr6XNwZPk7c+64SMmG2C5Be10PNGEG+E=
      timestamp: '2026-03-05T19:46:17Z'
      ref:
        tag: branch
        contents: release-25.11
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
