channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 1127f697e3448d7991b8f3c7c7cc223063fd848f
      hash: sha256-Zz7Awf6EG89OP1l7/CK3FkR514UkXkS84q7xpE4XWI8=
      timestamp: '2026-04-10T00:52:59Z'
    packages:
      - name: kernels.bash
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: 863c462d78dd3e9de7ca3516b28764ef0346a763
      hash: sha256-ikVevlyl0tMS+ThY+WOku08gVE6l39+P864qrSSMDB8=
      timestamp: '2026-04-10T04:14:04Z'
      ref:
        tag: branch
        contents: release-25.11
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
