channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 337090657d6ab73b8edcd6b8309fedee5e7a54e3
      hash: sha256-KSKIODWdrBn6CQmq32NfJJErKzlPSAxhmmsD9Oe6lnE=
      timestamp: '2026-03-05T07:26:30Z'
    packages:
      - name: kernels.octave
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: adcd3f4ca3f16307452bfe6224a89165cf0807b4
      hash: sha256-qr/4kyYMzBCDrF9bd8fzFJDFDoYOytLlKPgZKlP1vFs=
      timestamp: '2026-03-21T18:29:38Z'
      ref:
        tag: branch
        contents: release-25.11
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
