channels:
  - src:
      tag: fetch_from_github
      owner: codedownio
      repo: codedown-languages
      rev: 7633b48188cbfda7b128758ab65bc701954cdba0
      hash: sha256-TEfGgDgj2tFxL8BXIG/jKxyPgJmnfsbdB6AqOENZe4c=
      timestamp: '2026-03-31T08:22:26Z'
    packages:
      - name: kernels.octave
        settings:
          enable: true
      - name: language-servers.spellchecker
      - name: shells.zsh
  - src:
      tag: fetch_from_github
      owner: NixOS
      repo: nixpkgs
      rev: d8389e7cbb4f893444a237ecc20c5719e3c65144
      hash: sha256-eT0x5hmUK/r951TjO/Olwu/t4DJDsXkCcciv3hxLsTY=
      timestamp: '2026-03-31T07:27:47Z'
      ref:
        tag: branch
        contents: release-25.11
    packages: []
settings:
  default_kernel: $.channels[0].packages[0]
